spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service_db?currentSchema=order_service_user
    password: order_service_apps
    username: order_service_apps
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.fabiankevin: DEBUG
    org.zalando.logbook: TRACE
#    org.hibernate.stat: DEBUG
