server:
  port: 8080

spring:
  application:
    code: OS
    name: Order Service
  profiles:
    active: local


application:
  common:
    error-responses:
      ITEM_ALREADY_EXISTS:
        status: 400
        code: OS001
        message: '{0} is a duplicate item'


logging:
  level:
    org.hibernate.type: TRACE